# Generated by Django 3.1.3 on 2022-07-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20220714_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='made',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
